### ISSUE TITLE
node.js version?

### ISSUE THREAD

**Issue by andreas-ibm** [blgm/jfq#24]
Hey George,

I'm trying to run it on a raspberry pi running node v6, and hitting some seemingly basic errors, is this program only supported on node 8?

**Comment by blgm** [comment]
Excellent question @andreas-ibm.  I mostly use node v10, but a request for node v6 for the raspberry pi seems very reasonable.  To be honest, I'm simply glad to have a user!  I've just shipped `jfq@1.2.0` which should work node node v6.  It would be great to have feedback on whether it worked for you.  Any other feedback on jfq would be great too.

**Comment by blgm** [comment]
@andreas-ibm, I'm going to close this as a new version has been provided, and there has been no response.  If you have any feedback, then please feel free to add it here, or raise another issue.

**Comment by andreas-ibm** [comment]
Whoops, sorry, yeah, running around like a headless chicken! I'll give it a poke when I drag that set of Pies out again. Thanks for the fix!
